# Generated by Django 5.2.2 on 2025-06-08 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_id', models.IntegerField(unique=True)),
                ('nro_sigla_cicpse', models.IntegerField()),
                ('sigla_renicoa', models.CharField(blank=True, max_length=100, null=True)),
                ('otros_nro_registro', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_coleccion', models.CharField(max_length=200)),
                ('nombre_descriptivo', models.CharField(blank=True, max_length=200, null=True)),
                ('tipo_material', models.CharField(max_length=100)),
                ('anio_coleccion', models.CharField(blank=True, max_length=4, null=True)),
                ('forma_ingreso', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=200)),
                ('otros_datos', models.TextField(blank=True, null=True)),
                ('pais', models.CharField(blank=True, max_length=100, null=True)),
                ('provincia_region', models.CharField(blank=True, max_length=100, null=True)),
                ('departamento', models.CharField(blank=True, max_length=100, null=True)),
                ('localidad', models.CharField(blank=True, max_length=100, null=True)),
                ('sitio_arqueologico', models.CharField(blank=True, max_length=200, null=True)),
                ('datos_contextuales', models.TextField(blank=True, null=True)),
                ('altura_largo', models.FloatField(blank=True, null=True)),
                ('ancho_diametro_maximo', models.FloatField(blank=True, null=True)),
                ('espesor', models.FloatField(blank=True, null=True)),
                ('otras_alturas', models.FloatField(blank=True, null=True)),
                ('diametro_minimo', models.FloatField(blank=True, null=True)),
                ('otras_medidas', models.TextField(blank=True, null=True)),
                ('forma', models.CharField(blank=True, max_length=200, null=True)),
                ('tecnica', models.CharField(blank=True, max_length=200, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('adscripcion_cultural_temporal', models.CharField(blank=True, max_length=200, null=True)),
                ('estado_conservacion', models.CharField(choices=[('malo', 'Malo'), ('regular', 'Regular'), ('bueno', 'Bueno'), ('muy bueno', 'Muy Bueno')], max_length=50)),
                ('estado_estructural', models.CharField(choices=[('entero', 'Entero'), ('fragmentado', 'Fragmentado'), ('completo', 'Completo'), ('incompleto', 'Incompleto')], max_length=50)),
                ('estado_superficie', models.CharField(choices=[('sin_deterioro', 'Sin deterioro'), ('suciedad_superficial', 'Suciedad Superficial'), ('depositos_foraneos', 'Depósitos Foráneos')], max_length=50)),
                ('intervenciones', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateField()),
                ('nombre_apellido', models.CharField(max_length=200)),
                ('dni', models.IntegerField()),
                ('designacion', models.CharField(max_length=100)),
                ('contacto', models.CharField(max_length=50)),
            ],
        ),
    ]
