# Generated by Django 5.2.2 on 2025-06-08 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ficha_antropologia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ficha',
            name='adscripcion_cultural_temporal',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='altura_largo',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='ancho_diametro_maximo',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='contacto',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='datos_contextuales',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='designacion',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='diametro_minimo',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='espesor',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='estado_conservacion',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='estado_estructural',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='estado_superficie',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='fecha_registro',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='forma',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='id',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='intervenciones',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='localidad',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='nombre_apellido',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='otras_alturas',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='otras_medidas',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='provincia_region',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='sitio_arqueologico',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='tecnica',
        ),
        migrations.AlterField(
            model_name='ficha',
            name='forma_ingreso',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='nro_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='tipo_material',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
