# Generated by Django 5.2.2 on 2025-06-09 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cuentas", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="categoria",
        ),
        migrations.AddField(
            model_name="item",
            name="coleccion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="cuentas.coleccion",
            ),
        ),
        migrations.AlterField(
            model_name="area",
            name="nombre",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name="Categoria",
        ),
    ]
