# Generated by Django 5.2.2 on 2025-06-11 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cuentas", "0002_remove_item_categoria_item_coleccion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="privado",
            field=models.BooleanField(default=False),
        ),
    ]
