# Generated by Django 5.2.2 on 2025-06-11 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cuentas", "0003_item_privado"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="item",
            options={"permissions": []},
        ),
    ]
