# Generated by Django 5.2.2 on 2025-06-18 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cuentas", "0004_alter_item_options"),
        ("cuentas", "0005_auto_20250618_0035"),
    ]

    operations = []
