# Generated by Django 5.2.2 on 2025-06-18 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("noticias", "0002_noticia_aprobada_alter_noticia_portada_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="noticia",
            name="portada",
            field=models.ImageField(blank=True, null=True, upload_to="portadas/"),
        ),
    ]
