# Generated by Django 5.2.1 on 2025-06-17 18:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_id', models.IntegerField()),
                ('sigla_cicpse', models.IntegerField()),
                ('sigla_renicoa', models.CharField(blank=True, max_length=100)),
                ('otros_nros', models.CharField(blank=True, max_length=200)),
                ('nombre_coleccion', models.CharField(max_length=200)),
                ('nombre_descriptivo', models.CharField(blank=True, max_length=200)),
                ('tipo_material', models.CharField(max_length=100)),
                ('anio_coleccion', models.CharField(blank=True, max_length=20)),
                ('forma_ingreso', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=200)),
                ('otros_datos', models.TextField(blank=True)),
                ('pais', models.CharField(blank=True, max_length=100)),
                ('pais_region', models.CharField(blank=True, max_length=100)),
                ('departamento', models.CharField(blank=True, max_length=100)),
                ('localidad', models.CharField(blank=True, max_length=100)),
                ('sitio_arqueologico', models.CharField(blank=True, max_length=200)),
                ('datos_contextuales', models.TextField(blank=True)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('nombre_apellido', models.CharField(blank=True, max_length=200)),
                ('dni', models.IntegerField(blank=True, null=True)),
                ('designacion', models.CharField(blank=True, max_length=200)),
                ('contacto', models.CharField(blank=True, max_length=50)),
                ('forma', models.CharField(blank=True, max_length=100)),
                ('tecnica', models.CharField(blank=True, max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=100)),
                ('adscripcion_cultural_temporal', models.CharField(blank=True, max_length=100)),
                ('altura_largo', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('ancho_diametro_maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('espesor', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('otras_alturas', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('diametro_minimo', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('otras_medidas', models.CharField(blank=True, max_length=200)),
                ('estado_conservacion', models.CharField(blank=True, max_length=50)),
                ('estado_estructural', models.CharField(blank=True, max_length=50)),
                ('estado_superficie', models.CharField(blank=True, max_length=50)),
                ('deterioro_quimico', models.CharField(blank=True, max_length=50)),
                ('deterioro_mecanico', models.CharField(blank=True, max_length=50)),
                ('deterioro_biologico', models.CharField(blank=True, max_length=50)),
                ('intervenciones', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('intervenciones_investigacion', models.TextField(blank=True)),
                ('prestamos_exposiciones', models.TextField(blank=True)),
                ('ubicaciones_anteriores', models.TextField(blank=True)),
                ('documentacion_asociada', models.TextField(blank=True)),
                ('asociacion_otros_lotes_objetos', models.TextField(blank=True)),
                ('historia_objeto', models.TextField(blank=True)),
                ('otra_informacion', models.TextField(blank=True)),
                ('foto_sin_intervencion', models.ImageField(blank=True, null=True, upload_to='fotos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('foto_intervenido', models.ImageField(blank=True, null=True, upload_to='fotos/')),
                ('foto_rotulos', models.ImageField(blank=True, null=True, upload_to='fotos/')),
                ('otras_fotografias', models.ImageField(blank=True, null=True, upload_to='fotos/')),
            ],
        ),
    ]
